[[colors.indexed_colors]]
color = "#f4a261"
index = 16

[[colors.indexed_colors]]
color = "#d67ad2"
index = 17

[colors.bright]
black = "#575860"
blue = "#86abdc"
cyan = "#7ad5d6"
green = "#8ebaa4"
magenta = "#baa1e2"
red = "#d16983"
white = "#e4e4e5"
yellow = "#e0c989"

[colors.cursor]
cursor = "#666666"
text = "CellForeground"

[colors.normal]
black = "#393b44"
blue = "#719cd6"
cyan = "#63cdcf"
green = "#81b29a"
magenta = "#9d79d6"
red = "#c94f6d"
white = "#dfdfe0"
yellow = "#dbc074"

[colors.primary]
background = "#192330"
foreground = "#cdcecf"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Bizin Gothic Discord NF"
style = "Bold"

[font.bold_italic]
family = "Bizin Gothic Discord NF"
style = "Bold Italic"

[font.italic]
family = "Bizin Gothic Discord NF"
style = "Italic"

[font.normal]
family = "Bizin Gothic Discord NF"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[scrolling]
history = 0

[window]
opacity = 1.0

[window.dimensions]
columns = 160
lines = 60

[window.padding]
x = 0
y = 0
