[[plugins]]
repo             = 'Shougo/deoplete.nvim'
on_event         = 'InsertEnter'
hook_post_source = 'call deoplete#enable()'

[[plugins]]
repo     = 'Shougo/neosnippet.vim'
on_event = 'InsertEnter'

[[plugins]]
repo     = 'Shougo/neosnippet-snippets'
on_event = 'InsertEnter'

[[plugins]]
repo  = 'vim-perl/vim-perl'
on_ft = ['perl']

[[plugins]]
repo  = 'y-uuki/perl-local-lib-path.vim'
on_ft = ['perl']

[[plugins]]
repo  = 'motemen/xslate-vim'
on_ft = ['perl']

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html']

[[plugins]]
repo    = 'kannokanno/previm'
on_ft   = ['markdown']
depends = ['open-browser.vim']

[[plugins]]
repo  = 'Keithbsmiley/swift.vim'
on_ft = ['swift']

[[plugins]]
repo  = 'VimClojure'
on_ft = ['clojure']

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo  = 'zah/nim.vim'
on_ft = ['nim']

[[plugins]]
repo  = 'rhysd/vim-crystal'
on_ft = ['crystal']

[[plugins]]
repo  = 'udalov/kotlin-vim'
on_ft = ['kotlin']

[[plugins]]
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo  = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo  = 'OrangeT/vim-csharp'
on_ft = ['cs', 'csi', 'csx']

[[plugins]]
repo  = 'OmniSharp/omnisharp-vim'
on_ft = ['cs', 'csi', 'csx']
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'msbuild server/OmniSharp.sln'
  else
    let cmd = 'xbuild server/OmniSharp.sln'
  endif
'''

[[plugins]]
repo  = 'tpope/vim-dispatch'
on_ft = ['cs', 'csi', 'csx']

[[plugins]]
repo = 'taka84u9/vim-ref-ri'
on_ft = ['ruby']

[[plugins]]
repo = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo = 'eagletmt/ghcmod-vim'
on_ft = ['haskell']

[[plugins]]
repo = 'ujihisa/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo = 'ujihisa/ref-hoogle'
on_ft = ['haskell']

[[plugins]]
repo = 'ujihisa/unite-haskellimport'
on_ft = ['haskell']

