[[plugins]]
repo             = 'Shougo/deoplete.nvim'
on_event         = 'InsertEnter'
hook_post_source = 'call deoplete#enable()'

[[plugins]]
repo  = 'y-uuki/perl-local-lib-path.vim'
on_ft = ['perl']

[[plugins]]
repo  = 'motemen/xslate-vim'
on_ft = ['perl']

[[plugins]]
repo  = 'mattn/emmet-vim'
on_ft = ['html', 'eruby', 'eco']

[[plugins]]
repo    = 'tyru/open-browser.vim'
on_ft   = ['markdown']

[[plugins]]
repo    = 'kannokanno/previm'
on_ft   = ['markdown']
depends = ['open-browser.vim']

[[plugins]]
repo = 'taka84u9/vim-ref-ri'
on_ft = ['ruby']

[[plugins]]
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]]
repo    = 'AndrewRadev/vim-eco'
on_ft   = ['eco']
depends = ['vim-coffee-script']

