[tools]
awscli = { version = "2.34.37", symlink_bins = "true" }
elixir = "1.19.5"
erlang = "28.4"
flutter = "3.38.7"
fzf = "0.72.0"
ghq = "1.10.1"
github-cli = "2.91.0"
go = "1.26.2"
lazydocker = "0.25.2"
lazygit = "0.61.1"
lefthook = "2.1.6"
neovim = "0.12.2"
node = "24.14.1"
peco = "0.6.0"
perl = "5.42.2"
pnpm = "10.33.2"
python = "3.14.4"
ruby = "4.0.3"
saml2aws = "2.36.19"
sops = "3.12.2"
task = "3.50.0"
terraform = "1.14.9"
tree-sitter = "0.26.8"
usage = "3.2.1"
yamlfmt = "0.21.0"
yq = "4.53.2"
zig = "0.16.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
