[tools]
awscli = { version = "2.34.24", symlink_bins = "true" }
elixir = "1.19.5"
erlang = "28.4"
flutter = "3.38.7"
fzf = "0.71.0"
ghq = "1.9.4"
github-cli = "2.89.0"
go = "1.26.1"
lazydocker = "0.25.0"
lazygit = "0.60.0"
lefthook = "2.1.5"
neovim = "0.12.0"
node = "24.14.1"
peco = "0.6.0"
perl = "5.42.2"
pnpm = "10.33.0"
python = "3.14.3"
ruby = "4.0.2"
saml2aws = "2.36.19"
sops = "3.12.2"
task = "3.49.1"
terraform = "1.14.8"
tree-sitter = "0.26.8"
usage = "3.2.0"
yamlfmt = "0.21.0"
yq = "4.52.5"
zig = "0.15.2"

[settings]
experimental = true
idiomatic_version_file_enable_tools = []
